### PR TITLE
docs: add loopback 4 usage

### PR DESCRIPTION
**Pull request by shubhamp-sf**
[REST Connector](https://loopback.io/doc/en/lb4/REST-connector.html) page lacked the loopback 4 usage instructions. 
And loopback 2.x and 3.x usage doesn't hint much about possible steps for LB4.

So I added the instructions and linked details page of [calling REST APIs](https://loopback.io/doc/en/lb4/Calling-rest-apis.html).

Signed-off-by: Shubham Prajapat <shubham.prajapat@sourcefuse.com>

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [x] Commit messages are following our [guidelines](https://loopback.io/doc/en/contrib/git-commit-messages.html)

### CODE REVIEW

**Comment by shubhamp-sf** [comment]
@raymondfeng Can you please review this PR?
It's just docs stuff so won't take more than 2 mins.

**Review by dhmlau — APPROVED** [review]

**Comment by dhmlau** [comment]
@shubhamp-sf, thanks for the PR. Your changes LGTM. I'm not sure why CI is pending. Do you mind force pushing some changes (could just be making dummy changes, reverting it and squashing the commits) so that CI is forced to rerun again? Thanks.

**Comment by shubhamp-sf** [comment]
@dhmlau I guess, you need to manually run them?
image

**Comment by dhmlau** [comment]
It's probably because you're the first time contributor of this repo, it needs to "approve and review" before CI can start.

**Review by dhmlau — APPROVED** [review]

**Comment by dhmlau** [comment]
@shubhamp-sf, thanks for your contribution. Your PR has landed! 🎉

**Pull request merged**
